# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e22a95fdaeacdb346dadce924196f70e014381e0ac837e0109d060703494f75423c01762607c55a2f3775459302b2f592238e99c42412eefcf1310db7ed1587

test:
  secret_key_base: 7d779c9a82011d950c509bc8509a88923482caea0fe51f216715d082dc0c214abb94bfdbfb83acd43bfdd647fdcde7ab9c9406b49c6c8d9f82ee5de0ac74998d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
