version: "2"

services:
    mosq:
        image: toke/mosquitto:latest
        ports:
           - "1883:1883"
        volumes:
           - ./mosq/config1:/mqtt/config
           - ./mosq/log1:/mqtt/log
           - ./mosq/data1:/mqtt/data

    zoo1:
        image: zookeeper:3.4
        #restart: always
        ports:
           - "12181:2181"
           - "12888:2888"
           - "13888:3888"
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888
        volumes:
            - ./zk/data1:/data
            - ./zk/datalog1:/datalog
    zkdash:
        image: mruepp/zkdash:latest
        volumes:
            - ./zkdash/config:/config
        ports:
            - "8080:8000"
        depends_on:
            - zoo1

    kafka:
        image: mruepp/mqtt-kafka:latest
        #restart: always
        volumes:
            - ./kafka/data1:/data
            - ./kafka/logs1:/logs
        ports:
            - "9092:9092"
        environment:
            #- KAFKA_ADVERTISED_HOST_NAME=10.55.1.104
            #- KAFKA_ADVERTISED_LISTENERS=10.55.1.104:9092
            - KAFKA_ADVERTISED_HOST_NAME=kafka
            - KAFKA_ADVERTISED_LISTENERS=kafka:9092
            - KAFKA_BROKER_ID=-1
            - KAFKA_NUM_PARTITIONS=1
            - KAFKA_DEFAULT_REPLICATION_FACTOR=1
            #- KAFKA_ADVERTISED_HOST_NAME=172.18.0.7
            - KAFKA_ADVERTISED_PORT=9092
            #- JAVA_RMI_SERVER_HOSTNAME=10.55.1.104
            - JAVA_RMI_SERVER_HOSTNAME=kafka
            - ZOOKEEPER_CONNECTION_STRING=zoo1:2181
        depends_on:
            - zoo1
    kafka-manager:
          image: sheepkiller/kafka-manager:latest
          ports:
             - "8081:9000"
          environment:
            ZK_HOSTS: zoo1:2181
            KM_CONFIG: /opt/application.conf
          volumes:
             - ./km:/opt
          depends_on:
             - zoo1
             - kafka

    mosqtokafka:
        image: mruepp/mqtt-connect:latest
        environment:
              - CONNECT_FILE=connect-standalone.properties
        volumes:
              - ./mostokaf/logs1:/logs
              - ./mostokaf/config1:/kafka/config
        depends_on:
              - zoo1
              - mosq
              - kafka

    crate:
         image: jodok/crate:latest
         ports:
              - "4200:4200"
              - "4300:4300"
              - "5432:5432"
         volumes:
              - ./crate/data:/data
         environment:
              CRATE_HEAP_SIZE: 1g


