version: '2'

services:
  node-red:
    image: machinedata/node-red
    ports:
      - "1880:1880"
    network_mode: host
    volumes:
      - ./node-red/data:/data

  mosquitto:
    image: machinedata/mosquitto
    ports:
      - "1881:1881"
    network_mode: host
    volumes:
      - ./mosquitto/data:/data

  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    network_mode: host
    environment:
      #ZOO_MY_ID: 0
      ZOO_SERVERS: server.1=demo-01:2888:3888 server.2=demo-02:2888:3888 server.3=demo-03:2888:3888

  kafka:
    image: ches/kafka
    ports:
      - "9092:9092"
      - "7203:7203"
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      ZOOKEEPER_CONNECTION_STRING: demo-01:2181,demo-02:2181,demo-03:2181
      #KAFKA_AUTO_LEADER_REBALANCE_ENABLE: 'true'
      #JMX_PORT: "9999"
      #KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote.rmi.port=7203
    #volumes:
      #- /var/run/docker.sock:/var/run/docker.sock

  spark-master:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h demo-ro
    #hostname: master
    environment:
      MASTER: spark://demo-ro:7077
      SPARK_CONF_DIR: /conf
      #SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    network_mode: host
    volumes:
      - ./conf/master:/conf
      - ./data:/tmp/data

  spark-worker:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://demo-ro:7077
    #hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      #SPARK_PUBLIC_DNS: localhost
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    network_mode: host
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data
