version: '2'

services:
  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - 2181
      - 2888
      - 3888
    network_mode: host
    environment:
      ZOO_SERVERS: server.1=demo-01:2888:3888 server.2=demo-02:2888:3888 server.3=demo-03:2888:3888
